services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordRoot
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local