name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Build jar file
        run: |
          chmod +x ./gradlew
          ./gradlew clean test build

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp.jar
          path: build/libs/*.jar
          if-no-files-found: warn
          compression-level: 0
          overwrite: false
          include-hidden-files: false
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.7-6/x64
          JAVA_HOME_21_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.7-6/x64

#define deployJobs with build job artifact
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myappProduct.jar
          path: ./artifacts